#!/usr/bin/env python3
import os
import sys

import helpers
from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @scree_name")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    list_tweets = helpers.get_user_timeline(sys.argv[1], 50)


    for tweet in list_tweets:
        # analyze word
        score = analyzer.analyze(tweet)

        if score > 0.0:
            print(colored(str(score) + " " + str(tweet)
                        , "green"))
        elif score < 0.0:
            print(colored(str(score) + " " + str(tweet)
                        , "red"))
        else:
            print(colored(str(score) + " " + str(tweet)
                        , "yellow"))

if __name__ == "__main__":
    main()

